services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
  
  celery_worker:
    build: billing
    command: celery -A apps.broker.tasks worker --loglevel=info
    # volumes:
    #   - .:/apps
    # environment:
    #   - BROKER=redis://redis:6379/0
    #   - BACKEND=redis://redis:6379/1
    depends_on:
      - redis


  billing_service:
    build: billing
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db # Монтируем локальную папку data в папку /app/data внутри контейнера
      - ./logs:/app/logs # Монтируем локальную папку logs в папку /app/logs внутри контейнера для отслеживания логов
    # environment:
    #   - BROKER=redis://redis:6379/0
    #   - BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - celery_worker
  
  frontend:
    build: frontend
    ports:
      - "8001:8001"
    environment:
      - BACKEND_FASTAPI=http://billing_service:8000
    depends_on:
      - redis
      - celery_worker
      - billing_service


networks:
  backend:
